### ISSUE TITLE
Função - Analisar conectividade do Grafo

### ISSUE THREAD

**Issue by Ca-moes** [Ca-moes/MeatWagons#16]
Com a opção no menu:
- **Conectividade da origem**: através dos algoritmos de Pesquisa em Largura/Profundidade, será calculada a quantidade de esquadras, prisões e tribunais que podem ser alcançados a partir da origem selecionada. Estes pontos poderão ser apresentados ao utilizador.

É necessário algo que analise a conectividade

**Comment by g-batalhao-a** [comment]
Bua, xuif xuif, feitu
